### ISSUE TITLE
Possible catastrophic memory leak? [v10.1.0.13]

### ISSUE THREAD

**Issue by SoulCookie** [ThingEngineering/wowthing-collector#12]
Hi. Since auto-updating the Collector to v10.1.0.13 last night, each attempt I've made to log into a character has completely frozen WoW, to the point of needing to force-quit the game if it doesn't disconnect me on its own after a few minutes.

One of the other addon-modules I have installed shows rough memory footprints for addons, and within seconds of logging in, WoWthing Collector is using over **10x** the memory of the next-weightiest addon (over 300MB vs ~30MB).

By way of confirmation, disabling/not loading the Collector addon eliminates the problem.

**Comment by madcowfred** [comment]
Well that's fun. Um... can you try opening `WoWthing_Collector.toc` and commenting out (`#` at the start of the line) the `Modules/Bags.lua` line? I don't _think_ any of the others would be causing a mess :(

**Comment by SoulCookie** [comment]
I'm sorry to report that commenting out `Bags.lua` did not keep the hard-hang from happening again. Have another module (or set of modules) you'd like me to try commenting out instead?

**Comment by madcowfred** [comment]
If you don't mind playing whack-a-mole it's probably just all of them. If possible could you also check if it does it with no other addons enabled? Possibly a weird interaction with another addon... which I could see being `Modules/TimePlayed.lua`'s fault as it hooks a function.

**Comment by SoulCookie** [comment]
Don't mind at all. Won't have a chance to check for a few hours, though. Will report back after I do. 👍

**Comment by SoulCookie** [comment]
I can report **no issues** when the WoWthing Collector is loaded by itself. 👍

I have begun the addon narrowing process to find what combo causes the friction. More to come.

**Comment by SoulCookie** [comment]
Well, now having gone through the process of disabling all my addons and re-enabling them one-by-one, I'm not seeing the same freezing behavior at all. 

_[insert "Sure, Jan" gif here]_

I don't know why it wasn't working earlier, and why it's working just fine now (on the same character!), but it is.

Thanks, and sorry for any time wasted on this.

**Comment by SoulCookie** [comment]
(Should I close the issue, or do you want to?)

**Comment by madcowfred** [comment]
That's bizarre 😅 Thanks for doing the digging, hopefully it doesn't come up again but let me know if it does!
