### ISSUE TITLE
Returned: abnormally large memory footprint [v10.1.0.14]

### ISSUE THREAD

**Issue by SoulCookie** [ThingEngineering/wowthing-collector#13]
Regrettably I have to report that the memory leak/issue/_thing_ (ref #12) has happened again, after a night and a day of being nice and chill. 

The only pic I snapped of its ballooning size yesterday was, as I mentioned, ~300MB. Tonight I grabbed this pic of it over 900MB. 

![IMG_7600](https://github.com/ThingEngineering/wowthing-collector/assets/4214704/0a9da833-64cc-4451-a979-8aab8d6f2e10)

I'm gonna disable the Collector addon for my play session tonight; I'll try re-enabling it later tonight or tomorrow and see if things are better. If there are particular things you'd like me to test, I remain happy to do.

**Comment by madcowfred** [comment]
Sigh, wtf 😢 If you could try [v10.1.0.15](https://github.com/ThingEngineering/wowthing-collector/releases/tag/v10.1.0.15) at some point and let me know - if that fails, could you try editing `Addons\WoWthing_Collector\WoWthing_Collector.toc` and commenting out all of the modules:

```
Core.lua

# Modules/Achievements.lua
# Modules/Bags.lua
# Modules/CharacterMisc.lua
# Modules/Currencies.lua
# Modules/Guild.lua
# Modules/Location.lua
# Modules/Lockouts.lua
# Modules/MythicPlus.lua
# Modules/ProfessionEquipment.lua
# Modules/Quests.lua
# Modules/Reputations.lua
# Modules/Spells.lua
# Modules/TimePlayed.lua
# Modules/Transmog.lua
# Modules/Vault.lua
# Modules/WorldQuests.lua
# Modules/XP.lua
```

If that works, uncomment them and reload one by one. It sucks but I have no real idea what could possibly be causing the issue.

**Comment by SoulCookie** [comment]
Partial testing done tonight; will resume tomorrow.

Results so far are... maddening.

1. **_10.1.0.15, all modules:_** memory spike/ freeze ❌
2. **_10.1.0.15 (continues), no modules:_** seems fine ✅
3. **_adding in modules one at a time, cumulatively:_** ok ✅ `Achievements` thru `MythicPlus`
4. **_adding `ProfessionEquipment` to the cumulation:_** big spike ❌
5. **_enabling all modules EXCEPT `ProfessionEquipment`:_** ok ✅
6. **_enabling ONLY `ProfessionEquipment`:_** seems fine, _annoyingly_ ✅
7. **_retrying the partial, formerly-spiking combo from step 4:_** damn thing works fine 😠✅
8. **_re-enabling ALL modules (repeating step 1):_** again, the infernal thing behaves normally 😡✅

So I don't know quite what to try tomorrow. I saw the biggest spike from adding `Modules/ProfessionEquipment.lua` into the mix, but it didn't appear to be a repeat offender, so I don't know if it was coincidence or not. 

On the theory that whatever is contributing to the spikiness is getting somehow cached and so smoothed over, I'm going to do some testing with different characters and see if I can identify any repeatable steps.

**Comment by madcowfred** [comment]
Hrm. I could see it infinitely retrying profession things if it failed to get item info the first time, I'll push a fix for that stupidity and see if it helps

**Comment by madcowfred** [comment]
If you can give [v10.1.0.16](https://github.com/ThingEngineering/wowthing-collector/releases/tag/v10.1.0.16) a try at some point that'd be cool, in theory that makes profession stuff less likely to consume your entire computer.

**Comment by SoulCookie** [comment]
10.1.0.16 installed. 👍

I'll run through the investigative steps with it if the memory spike rears its head again, and will report back. 🔍🤓

**Comment by SoulCookie** [comment]
Checking in: After several hours of running .16, I've had no repeat incidents.

Fingers crossed that the streak holds. 😅

**Comment by SoulCookie** [comment]
Updated to x.17. Still running without encountering problems. 👍

**Comment by SoulCookie** [comment]
Well, at the risk of angering the spirits of Comedy and Irony, I think the problem is resolved and this ticket can be closed. (I'm willing to keep checking in over the coming days if you'd rather keep it open a bit longer.)

**Comment by madcowfred** [comment]
Should be good now, thanks for narrowing it down to profession equipment - I looked at that a few times and went "yeah that looks right" when it absolutely was not :(
