### ISSUE TITLE
Performance issues/freezing

### ISSUE THREAD

**Issue by V1P3R** [ThingEngineering/wowthing-collector#15]
The game freezes on any character with this enabled.
Can only get it to work when I load it separately after logging in first and reloading UI.
Some throttling needed probably. Never had issues with AllTheThings, which has a LUA DB 3 times as big.

**Comment by madcowfred** [comment]
Like locks up completely, or lags for a while on logging in? Either way, is there any way you can track down which addon(s) it interacts badly with? I run a fairly wide variety (including ATT) and have never run into this or even had reports of it.

**Comment by V1P3R** [comment]
How can I do that? I run quite a large list of addons.
BTW, it does not lock up on my non70 alts with same addons.

**Comment by madcowfred** [comment]
I've just pushed [v10.1.7.4](https://github.com/ThingEngineering/wowthing-collector/releases/tag/v10.1.7.4) with some changes that might help, not really sure what else to try otherwise

**Comment by V1P3R** [comment]
Tried it out right away, same issue. locks up completely (waiting for several minutes, nothing happens)
Tried without ATT, same thing. Tried without WeakAuras, same thing. Those 2 are my major resource hogs.
And still, on lower level chars with all addons enabled, with TradeSkillMaster in extra also enabled (I have that disabled on my more frequented characters due to performance issues) there are no issues present.

Tried with commenting out Modules\ProfessionEquipment.lua as I saw that was a culprit in the past, had the same issues.

Commented out Modules\WorldQuests.lua and DB\WorldQuests.lua as a possible culprit, as those are very different on 60s and 70s.
Surprisingly it works like a charm without the WQ module.

**Comment by V1P3R** [comment]
Was happy too early.
Having the same issues on another char even with the WQ module and DB disabled.

Disabled LibRealmInfo (the naming LibRealmInfo17janekjl raised eyebrows), re-enabled WQs, worked like a charm, on 3 characters already.

**Comment by madcowfred** [comment]
If you can work out which module is locking up that would help, I have no idea otherwise. None of the modules should be able to get stuck in an infinite loop, they don't call their own functions in any way other than a "run this on the next frame" timer 😐

The `LibRealmInfo17janekjl` thing is just a manually updated `LibRealmInfo` with a bug fix and current realms, there haven't been any new releases of it in years. I should probably just call it normal `LibRealmInfo`, bump the version, and rely on `LibStub` using the highest version.

**Comment by Incandio** [comment]
Hi, in Remix I'm getting a similar prob as above, the conflict seems to be with BetterWardrobe but I'm not sure. When logging in on a Remix toon with both enabled, game crashes (FPS drops to zero and freezes). Loading one first and then enabling the other and reloading the Interface works OK, however, including if I exit the game. After a while offline, the problem reoccurs.

**Comment by madcowfred** [comment]
Hopefully fixed with 11.0.2.5+

**Comment by obroithe** [comment]
I am still having this issue with the latest version.

**Comment by madcowfred** [comment]
Anyone still having issues here, can you give [v11.0.2.11](https://github.com/ThingEngineering/wowthing-collector/releases/tag/v11.0.2.11) a try? It will only do a full scan once per client build, and it also has a more efficient method of scanning which makes it roughly 3x faster for me.
