### ISSUE TITLE
Bags in Items on wowthing

### ISSUE THREAD

**Issue by vandiel01** [ThingEngineering/wowthing-collector#23]
Bags are not updating properly to new bags I put on each toons, now Im not sure which I had it on :)
![image](https://github.com/user-attachments/assets/2c1639ea-2392-486c-a101-b70939f2d611)

**Comment by madcowfred** [comment]
Should be fixed with v11.0.2.10

**Comment by vandiel01** [comment]
Confirmed :)  Thanks again!
