### ISSUE TITLE
Realm info not working with non-english realm

### ISSUE THREAD

**Issue by Leomaradan** [ThingEngineering/wowthing-collector#5]
It seem that the LibRealmInfo:GetRealmInfoByUnit query on line 515 does not return any information

```lua
local _, realm, _, _, _, _, region, _, _, realmEnglish = LibRealmInfo:GetRealmInfoByUnit("player")
```
The realm and realmEnglish are nil, so the addon crash on the line 517

I'm on a French client

**Comment by Leomaradan** [comment]
The PR [https://github.com/janekjl/LibRealmInfo/pull/3/commits](url) on LibRealmInfo Repo seems to correct the issue

**Comment by madcowfred** [comment]
Applied that PR in v9.2.0.8, let me know if that fixes things for you

**Comment by Leomaradan** [comment]
Hi, this it perfect, thank you :)
