### ISSUE TITLE
Lua Error in garrisons

### ISSUE THREAD

**Issue by zalidthebur** [ThingEngineering/wowthing-collector#7]
Date: 2022-09-02 23:00:52
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\WoWthing_Collector\Collector.lua line 1667:
   bad argument #1 to 'ipairs' (table expected, got nil)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ipairs()
   [string "@WoWthing_Collector\Collector.lua"]:1667: ScanGarrison()
   [string "@WoWthing_Collector\Collector.lua"]:1659: ScanGarrisons()
   [string "@WoWthing_Collector\Collector.lua"]:379: Timer()
   [string "@WoWthing_Collector\Collector.lua"]:435:
      WoWthing_Collector\Collector.lua:435
   [string "@..\SharedXML\C_TimerAugment.lua"]:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  swatter, v<%version%> (<%codename%>)
  WowheadLooter, v90207
  Ace3, vRelease-r1259
  AchievementsReminder, v
  AckisRecipeList, v9.1.0.1
  AckisRecipeListQuickScan, v7.3.0.1
  ACP, v3.5.7 
  AddonFactory, v9.2.006
  AdiBags, vv1.9.36
  AdvancedInterfaceOptions, v1.7.2
  AllTheThings, vSL-2.9.4
  Altoholic, v9.2.006
  Armory, vv16.6.0
  ArmoryGuildBank, vv16.6.0
  AskMrRobot, v113
  Auctionator, v9.2.32
  BadBoy, vv9.2.4
  BarrelsOEasy, v1.2.02
  BattlePetDailyTamer, v3.1.11
  BattlePetBattleUITweaks, v2.0.12
  BattlePetBreedID, vv1.21.1
  BattlePetCageMatch, vV3.2
  BonusRollPreview, v90000.48-Release
  BtWObjectiveFilter, v1.3
  BtWQuests, v2.17.0
  BtWQuestsBattleForAzeroth, v53.14
  BtWQuestsBattleForAzerothPrologue, v15.6
  BtWQuestsShadowlands, v6.3
  BtWQuestsShadowlandsPrologue, v1.8
  BuyEmAll, v3.5.11
  CanIMogIt, v9.2.5v1.33
  Chinchilla, vv2.12.2
  ClassTimer, v2.4.90001.1
  Collectinator, v9.0.2
  Collectionator, v0.95
  CollectMe, v2.11
  ConfirmSP, v0.21.07.06
  CovenantMissionHelper, v3.2.0
  DataStore, v2022.08.05
  DataStoreAchievements, v9.2.004
  DataStoreAgenda, v9.2.004
  DataStoreAuctions, v9.2.004
  DataStoreCharacters, v2022.06.05
  DataStoreContainers, v9.2.004
  DataStoreCrafts, v9.2.004
  DataStoreCurrencies, v9.2.004
  DataStoreGarrisons, v9.2.004
  DataStoreInventory, v9.2.004
  DataStoreMails, v2022.06.05
  DataStorePets, v9.2.004
  DataStoreQuests, v9.2.004
  DataStoreReputations, v9.2.004
  DataStoreSpells, v2022.06.05
  DataStoreStats, v9.2.004
  DataStoreTalents, v9.2.004
  DBMCore, vfa8a9ff
  DBMStatusBarTimers, vfa8a9ff
  DBMVPVEM, v6746e8a
  DeathAlerts, v1.2
  Decursive, v2.7.8.6
  DejaCharacterStats, vR90205r1
  Dejunk, v9.1.2
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyDelete, v9.0.1
  EasyMail, v4.4.9b
  EasyScrap, v31
  ExaltedPlus, v15
  FactionAddict, v1.72
  FamilyFamiliarHelper, v1.4.11
  FishingBuddy, v1.16.11
  FlaresThatWork, vr47
  FocusHealthPercent, v4.0.1
  GarrisonMissionManager, vv62
  GTFO, v4.68
  GuildRosterManager, v1.92991
  GuildBankSnapshots, vv2.0.9
  GuildCheck, vv 2.5.1
  HandyNotes, vv1.6.6
  HandyNotesArgus, vv0.36
  HandyNotesBattleForAzeroth, v10
  HandyNotesBattleForAzerothTreasures, vv25
  HandyNotesBrokenShore, vv1.49
  HandyNotesDungeonLocations, v1.54
  HandyNotesLegionTreasures, vv27
  HandyNotesMistsOfPandariaTreasures, vv18
  HandynotesPandaria, v1.5.3
  HandyNotesShadowlandsTreasures, vv68
  HandyNotesTreasureHunter, vv26
  HandyNotesWorldMapButton, v90200.01-Retail
  idTip, v10.1.1
  Immersion, v1.4.4
  InFlightLoad, v9.2.0
  InstanceAchievementTracker, v3.43.0
  InterruptNoSpam, v1.8.7
  KibQuestMobs, v1.15
  LargerMacroIconSelection, vv1.7.2
  LoggerHeadLite, v1.5.6
  LootSpecSwapper, v9.2.7.01
  MasterPlanA, vA
  MaxDps, v9.1.5
  MinimalArchaeology, v9.2.0.2
  MinimapButtonFrame, v3.2.2
  MinimapButtonFrameSkinPack, v3.0.1b
  mOnArsWardrobeHelper, v1.22
  MRT, v4650
  Notes, v9.1.1
  NPCTime, v1.0.8
  Ogrilastone, v1.5
  Omen, v3.2.4
  Overachiever, v1.1.5
  OverachieverCache, v1.1.5
  OverachieverTabs, v1.1.5
  OverachieverTrade, v1.1.5
  PakuTotems, v1.62
  PetBattleMaster, v9.0.1
  PetTracker, v9.2.0
  PetTrackerConfig, v
  PetTrackerJournal, v
  Plexus, vv2.2.40
  PointBlankSniper, v5.9
  ProtoformSynthesisFieldJournal, v1.2.10
  Quartz, v3.6.12
  QuestSounds, v901-2020.10.14
  QuickMark, v
  QuizHelper, v
  RaidAchieveFilter, v2.0.5
  RareScanner, v9.2.7
  Rematch, v4.12.1
  SavedInstances, v9.2.4
  SetCollector, v3.3.8
  SharedMediaCausese, v
  SilverDragon, vv90205.2
  SilverDragonBattleForAzeroth, vv90205.2
  SilverDragonBurningCrusade, vv90205.2
  SilverDragonCataclysm, vv90205.2
  SilverDragonLegion, vv90205.2
  SilverDragonMists, vv90205.2
  SilverDragonOverlay, vv90205.2
  SilverDragonRangeExtender, vv90205.2
  SilverDragonShadowlands, vv90205.2
  SilverDragonVanilla, vv90205.2
  SilverDragonWarlords, vv90205.2
  SilverDragonWrath, vv90205.2
  SkillHelper, vv4.1.13
  SoulshapeJournal, v1.2.1
  Stubby, v<%version%> (<%codename%>)
  SuperDuperMacro, vretail 9.0.1.2, classic 1.13.5.4
  TargetHealthPercent, v5.0
  tdBattlePetScript, v9.0.1
  tdBattlePetScriptRematch, v80100.01
  TellMeWhen, v9.2.3
  TheUndermineJournal, v5.6.20220830
  TidyPlatesThreatPlates, v10.4.2
  TLDRMissions, v9.2-129
  TokenSplainer, vr04
  TomTom, vv3.1.4
  TradeSkillMaster, vv4.11.42
  TradeSkillMasterAppHelper, vv4.0.22
  tullaRange, v9.2.1
  VenturePlan, v4.30
  WarfrontRareTracker, v1.2.6
  WeakAuras, v4.1.2
  WorldQuestTracker, v
  WoWthingCollector, v9.2.7.7
  XanDurability, v5.0
  ZerethMortisPuzzleHelper, v1.5.1
  ZygorGuidesViewer, v8.1
  BlizRuntimeLib_enUS v9.2.7.90207 <none>
  (ck=1287)

**Comment by madcowfred** [comment]
Oops. v9.2.7.8 released, should fix that
