### ISSUE TITLE
Addon causes Elvui Bags to not process items

### ISSUE THREAD

**Issue by mohcow** [ThingEngineering/wowthing-collector#9]
Elvui Bags has a function where it queue/scans inventory etc. to show fancy item quality border, itemlevel, BoE, anima value etc. Sadly this does not work when Wowthing is enable. I'm not a programer, but in the Elvui discord it was explained that wowthing and elvui probably scan at the same time(f.e. PLAYER_ENTERING_WORLD) causing elvui to time out, resulting in no fancy item quality borders etc.

**Comment by madcowfred** [comment]
Yeah, it also breaks the same thing with AdiBags. I haven't worked out what I'm meant to be doing differently to fix it :(

**Comment by mohcow** [comment]
Maybe WoWUiDev Discord or the Elvui guys can help.

**Comment by madcowfred** [comment]
Can you give v10.0.0.4 a try and see if that helps at all?

**Comment by mohcow** [comment]
Still happening, might have gone down from 100% bugging out Elvui to 90%. On some /reloadui / character logins is fine, but most of the time it's still bugged.

**Comment by madcowfred** [comment]
Blah. I can break AdiBags, with only AdiBags enabled, purely by taking an item out of the mail. AdiBags/ElvUI both don't use `C_Item.IsItemDataCachedByID`, I'm not sure if unconditionally calling GetContainerItemInfo is what causes the breakage but I'm out of ideas for now.

WoW's 10.0.2 patch moves container functions to a new namespace, maybe they magically fixed this weirdness at the same time, will check next week.

**Comment by mohcow** [comment]
This issue is still happening.
